FROM node:12.17-alpine3.11

WORKDIR /home/pptruser/app

# Puppeteer deps
RUN apk --update add --no-cache \
  chromium \
  nss \
  freetype \
  freetype-dev \
  harfbuzz \
  ca-certificates \
  ttf-freefont \
  ttf-liberation \
  git && \
  addgroup -S pptruser && adduser -S -g pptruser pptruser && \
  mkdir -p /home/pptruser/Downloads /app && \
  chown -R pptruser:pptruser /home/pptruser && \
  chown -R pptruser:pptruser /app && \
  git clone https://github.com/petersolopov/carbonara.git /home/pptruser/app && \
  npm ci $npm-ci-params

USER pptruser

EXPOSE 3000
CMD ["npm", "start"]
